api:
  endpoint: /api
server:
  port: 8081

#default
---
spring:
  config:
    activate:
      on-profile: default
  jwt:
    secret: 1234
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:test;MODE=MYSQL;
    driver-class-name: org.h2.Driver
    username: sa
    password: 1234
    initialization-mode: always
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql
  sql:
    init:
      mode: always
  jpa:
    generate-ddl: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        format_sql: true
        show_sql: true
        hbm2ddl:
          auto: none

#test
---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:test;MODE=MYSQL;
    driver-class-name: org.h2.Driver
    username: sa
    password: 1234
    initialization-mode: always
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql
    sql:
      init:
        mode: always
    jpa:
      generate-ddl: false
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL57Dialect
          format_sql: true
          show_sql: true
          hbm2ddl:
            auto: none
